"""
AI Guardrails - Validate AI outputs to prevent predictions, new numbers, or prescriptive advice.
Ensures AI remains an interpreter, not a decision-maker.
"""

import re
from typing import Dict, List, Tuple, Optional


def sanitize_context(context_dict: Dict) -> Dict:
    """
    Sanitize context to ensure it contains only permitted content.
    
    Rules:
    - Only KPIs (scalars), insights, and small table snippets (max 10 rows)
    - No raw DataFrames or large datasets
    - No sensitive data (if applicable)
    
    Args:
        context_dict: Context dict from context_builder
    
    Returns:
        Sanitized context dict
    """
    sanitized = {
        "kpis": context_dict.get("kpis", {}),
        "insights": context_dict.get("insights", []),
        "table_snippets": {},
        "trends": context_dict.get("trends", {})
    }
    
    # Limit table snippets to max 10 rows each
    for key, value in context_dict.get("table_snippets", {}).items():
        if isinstance(value, list):
            sanitized["table_snippets"][key] = value[:10]
        else:
            sanitized["table_snippets"][key] = value
    
    # Limit insights to max 20
    sanitized["insights"] = sanitized["insights"][:20]
    
    return sanitized


def validate_llm_output(
    llm_text: str,
    facts_used: List[str],
    strict: bool = True
) -> Tuple[bool, Optional[str]]:
    """
    Validate LLM output to detect forbidden patterns.
    
    Checks for:
    1. Forbidden prediction/forecast language
    2. New numbers not present in facts_used (if strict=True)
    3. Prescriptive advice ("you should", "you must")
    
    Args:
        llm_text: Text generated by LLM
        facts_used: List of facts from deterministic answer
        strict: If True, also check for new numbers
    
    Returns:
        (is_valid, error_message)
        - is_valid: True if output passes validation
        - error_message: Description of violation (if any)
    """
    # Check for forbidden language
    forbidden_check = _contains_forbidden_language(llm_text)
    if forbidden_check[0]:
        return (False, f"Forbidden language detected: {forbidden_check[1]}")
    
    # Check for new numbers (if strict mode)
    if strict:
        new_numbers = _detect_new_numbers(llm_text, facts_used)
        if new_numbers:
            return (False, f"New numbers detected that were not in facts: {new_numbers[:3]}")
    
    return (True, None)


def _contains_forbidden_language(text: str) -> Tuple[bool, Optional[str]]:
    """
    Check if text contains forbidden prediction/recommendation language.
    
    Returns:
        (contains_forbidden, matched_phrase)
    """
    forbidden_phrases = [
        # Prediction/forecast
        "will likely",
        "will probably",
        "expected to",
        "expect to",
        "probability",
        "probable",
        "forecast",
        "predict",
        "prediction",
        "in the future",
        "going forward",
        "will be",
        "will have",
        "will increase",
        "will decrease",
        "will improve",
        "will worsen",
        
        # Prescriptive advice
        "you should",
        "you must",
        "you need to",
        "i recommend",
        "i suggest",
        "recommend that",
        "suggest that",
        "advise",
        "advised",
        
        # Probability/confidence
        "likely to",
        "unlikely to",
        "high chance",
        "low chance",
        "confidence",
        "confident that"
    ]
    
    text_lower = text.lower()
    
    for phrase in forbidden_phrases:
        if phrase in text_lower:
            return (True, phrase)
    
    return (False, None)


def _detect_new_numbers(llm_text: str, facts_used: List[str]) -> List[str]:
    """
    Detect if LLM introduced new numbers not present in facts_used.
    
    Returns:
        List of new numbers found (empty if none)
    """
    # Extract all numbers with € from LLM text
    llm_numbers = _extract_currency_numbers(llm_text)
    
    # Extract all numbers with € from facts
    facts_text = " ".join(facts_used)
    facts_numbers = _extract_currency_numbers(facts_text)
    
    # Find new numbers (with tolerance for rounding)
    new_numbers = []
    for llm_num in llm_numbers:
        found_match = False
        for fact_num in facts_numbers:
            # Allow 1% tolerance for rounding
            if abs(llm_num - fact_num) / max(fact_num, 1) < 0.01:
                found_match = True
                break
        
        if not found_match:
            new_numbers.append(f"€{llm_num:,.0f}")
    
    return new_numbers


def _extract_currency_numbers(text: str) -> List[float]:
    """
    Extract all currency numbers from text (e.g., €50,000 -> 50000.0).
    """
    # Pattern: €XX,XXX or €XX or €X.X
    pattern = r'€\s*([0-9,]+(?:\.[0-9]+)?)'
    matches = re.findall(pattern, text)
    
    numbers = []
    for match in matches:
        try:
            # Remove commas and convert to float
            num = float(match.replace(",", ""))
            numbers.append(num)
        except:
            pass
    
    return numbers


def apply_guardrails(
    llm_output: str,
    deterministic_answer: str,
    facts_used: List[str],
    strict: bool = True
) -> Tuple[str, bool, Optional[str]]:
    """
    Apply all guardrails and return safe output.
    
    If validation fails, returns deterministic_answer as fallback.
    
    Args:
        llm_output: Text from LLM
        deterministic_answer: Fallback deterministic text
        facts_used: List of facts
        strict: Enable strict number checking
    
    Returns:
        (final_output, was_blocked, block_reason)
        - final_output: LLM output if valid, else deterministic answer
        - was_blocked: True if LLM output was blocked
        - block_reason: Reason for blocking (if any)
    """
    is_valid, error_msg = validate_llm_output(llm_output, facts_used, strict=strict)
    
    if is_valid:
        return (llm_output, False, None)
    else:
        return (deterministic_answer, True, error_msg)


def check_transformers_available() -> bool:
    """
    Check if transformers library is available.
    Used to gracefully disable AI features if not installed.
    """
    try:
        import transformers
        return True
    except ImportError:
        return False
